#pragma checksum "C:\Users\egrou\source\repos\food\food\Site.Master" "{8829d00f-11b8-4213-878b-770e8597ac16}" "7F9E0AE2C73A90E12C466279F165C6D41C303D872B9400662F0C8DBB32FFE6F7"
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 12 "C:\Users\egrou\source\repos\food\food\Site.Master"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 12 "C:\Users\egrou\source\repos\food\food\web.config"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 12 "C:\Users\egrou\source\repos\food\food\Site.Master"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 15 "C:\Users\egrou\source\repos\food\food\Site.Master"
    using Microsoft.AspNet.Web.Optimization.WebForms;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 12 "C:\Users\egrou\source\repos\food\food\Site.Master"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 12 "C:\Users\egrou\source\repos\food\food\Site.Master"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 12 "C:\Users\egrou\source\repos\food\food\Site.Master"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class site_master : global::food.SiteMaster {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.site_master.@__PageInspector_LoadHelper("SetTraceData");
        
        private static System.Reflection.MethodInfo @__PageInspector_BeginRenderTracingMethod = global::ASP.site_master.@__PageInspector_LoadHelper("BeginRenderTracing");
        
        private static System.Reflection.MethodInfo @__PageInspector_EndRenderTracingMethod = global::ASP.site_master.@__PageInspector_LoadHelper("EndRenderTracing");
        
        private System.Web.UI.ITemplate @__Template_MainContent;
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public site_master() {
            ((global::food.SiteMaster)(this)).AppRelativeVirtualPath = "~/Site.Master";
            if ((global::ASP.site_master.@__initialized == false)) {
                global::ASP.site_master.@__stringResource = this.ReadStringResource();
                global::ASP.site_master.@__initialized = true;
            }
            this.ContentPlaceHolders.Add("maincontent");
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(this.Context.ApplicationInstance));
            }
        }
        
        [TemplateContainer(typeof(food.SiteMaster))]
        [TemplateInstanceAttribute(System.Web.UI.TemplateInstance.Single)]
        public virtual System.Web.UI.ITemplate Template_MainContent {
            get {
                return this.@__Template_MainContent;
            }
            set {
                this.@__Template_MainContent = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n<!DOCTYPE html>\r\n\r\n<html lang=\"zh\">\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        105,
                        41,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.WebTools.BrowserLink.Runtime.WebForms.TraceHelpers, Microsoft.WebTools." +
                    "BrowserLink.Tracing, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f1" +
                    "1d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.site_master.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.site_master.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        private void @__PageInspector_BeginRenderTracing(object[] parameters) {
            if ((global::ASP.site_master.@__PageInspector_BeginRenderTracingMethod != null)) {
                global::ASP.site_master.@__PageInspector_BeginRenderTracingMethod.Invoke(null, parameters);
            }
        }
        
        private void @__PageInspector_EndRenderTracing(object[] parameters) {
            if ((global::ASP.site_master.@__PageInspector_EndRenderTracingMethod != null)) {
                global::ASP.site_master.@__PageInspector_EndRenderTracingMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlMeta)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlMeta))));
            }
            else {
                
                #line 7 "C:\Users\egrou\source\repos\food\food\Site.Master"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
                
                #line default
                #line hidden
            }
            
            #line 7 "C:\Users\egrou\source\repos\food\food\Site.Master"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("http-equiv", "Content-Type");
            
            #line default
            #line hidden
            
            #line 7 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Content = "text/html; charset=utf-8";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        173,
                        69,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control5() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlMeta)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlMeta))));
            }
            else {
                
                #line 8 "C:\Users\egrou\source\repos\food\food\Site.Master"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
                
                #line default
                #line hidden
            }
            
            #line 8 "C:\Users\egrou\source\repos\food\food\Site.Master"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("charset", "utf-8");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        248,
                        24,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control6() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlMeta)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlMeta))));
            }
            else {
                
                #line 9 "C:\Users\egrou\source\repos\food\food\Site.Master"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
                
                #line default
                #line hidden
            }
            
            #line 9 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Name = "viewport";
            
            #line default
            #line hidden
            
            #line 9 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Content = "width=device-width, initial-scale=1.0";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        278,
                        72,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control7() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlTitle)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlTitle))));
            }
            else {
                
                #line 10 "C:\Users\egrou\source\repos\food\food\Site.Master"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
                
                #line default
                #line hidden
            }
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control7));
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        356,
                        7,
                        false});
            return @__ctrl;
        }
        
        private void @__Render__control7(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Site.Master",
                        363,
                        17,
                        false});
            
            #line 10 "C:\Users\egrou\source\repos\food\food\Site.Master"
@__w.Write(System.Web.HttpUtility.HtmlEncode( Page.Title ));

            
            #line default
            #line hidden
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Site.Master",
                        380,
                        11,
                        true});
            @__w.Write(" - 服務體 菜單系統");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Site.Master",
                        391,
                        8,
                        false});
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.PlaceHolder @__BuildControl__control8() {
            global::System.Web.UI.WebControls.PlaceHolder @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.PlaceHolder)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.PlaceHolder))));
            }
            else {
                
                #line 12 "C:\Users\egrou\source\repos\food\food\Site.Master"
                @__ctrl = new global::System.Web.UI.WebControls.PlaceHolder();
                
                #line default
                #line hidden
            }
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control8));
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        407,
                        110,
                        false});
            return @__ctrl;
        }
        
        private void @__Render__control8(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Site.Master",
                        449,
                        44,
                        false});
            
            #line 13 "C:\Users\egrou\source\repos\food\food\Site.Master"
@__w.Write(System.Web.HttpUtility.HtmlEncode( Scripts.Render("~/bundles/modernizr") ));

            
            #line default
            #line hidden
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.AspNet.Web.Optimization.WebForms.BundleReference @__BuildControl__control9() {
            global::Microsoft.AspNet.Web.Optimization.WebForms.BundleReference @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((Microsoft.AspNet.Web.Optimization.WebForms.BundleReference)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(Microsoft.AspNet.Web.Optimization.WebForms.BundleReference))));
            }
            else {
                
                #line 15 "C:\Users\egrou\source\repos\food\food\Site.Master"
                @__ctrl = new global::Microsoft.AspNet.Web.Optimization.WebForms.BundleReference();
                
                #line default
                #line hidden
            }
            
            #line 15 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Path = "~/Content/css";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        523,
                        62,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control10() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlLink)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlLink))));
            }
            else {
                
                #line 16 "C:\Users\egrou\source\repos\food\food\Site.Master"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
                
                #line default
                #line hidden
            }
            
            #line 16 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Href = "~/favicon.ico";
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\egrou\source\repos\food\food\Site.Master"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "shortcut icon");
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\egrou\source\repos\food\food\Site.Master"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "image/x-icon");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        591,
                        69,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control11() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlLink)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlLink))));
            }
            else {
                
                #line 17 "C:\Users\egrou\source\repos\food\food\Site.Master"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
                
                #line default
                #line hidden
            }
            
            #line 17 "C:\Users\egrou\source\repos\food\food\Site.Master"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Href = "//code.jquery.com/ui/1.13.3/themes/smoothness/jquery-ui.css";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        666,
                        90,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control12() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    <script>\r\n        window.onload = function () {\r\n            islogin();\r\n  " +
                    "      };\r\n\r\n        function islogin() {\r\n            if ($(\"#menu_infor\").lengt" +
                    "h > 0) {\r\n                //console.log(\'有找到元件\');\r\n                at_start = do" +
                    "cument.cookie.indexOf(\"person=\");\r\n                if (at_start != -1) {\r\n      " +
                    "              //console.log(\'有找到cookie\');\r\n                    //console.log(dec" +
                    "odeURI(document.cookie.split(\';\')[0].split(\'&\')[1]).split(\'=\')[1]);\r\n           " +
                    "         document.getElementById(\"menu_infor\").innerHTML = decodeURI(document.co" +
                    "okie.split(\';\')[0].split(\'&\')[1]).split(\'=\')[1] + \" 登入中\";\r\n                    d" +
                    "ocument.getElementById(\"login_inout\").innerHTML = \"管理登出\";\r\n                } els" +
                    "e {\r\n                    document.getElementById(\"menu_infor\").innerHTML = \"菜單系統" +
                    "\";\r\n                    document.getElementById(\"login_inout\").innerHTML = \"管理登入" +
                    "\";\r\n                }\r\n            }\r\n        }\r\n        function parseCookie() " +
                    "{\r\n            var cookieObj = {};\r\n            var cookieAry = document.cookie." +
                    "split(\';\');\r\n            var cookie;\r\n            for (var i = 0, l = cookieAry." +
                    "length; i < l; ++i) {\r\n                cookie = jQuery.trim(cookieAry[i]);\r\n    " +
                    "            cookie = cookie.split(\'=\');\r\n                cookieObj[cookie[0]] = " +
                    "cookie[1];\r\n            }\r\n            return cookieObj;\r\n        }\r\n        fun" +
                    "ction getCookieByName(name) {\r\n            var value = parseCookie()[name];\r\n   " +
                    "         if (value) {\r\n                value = decodeURIComponent(value);\r\n     " +
                    "       }\r\n            return value;\r\n        }\r\n\r\n    </script>\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        756,
                        1586,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 6 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl1;
            
            #line 6 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl2;
            
            #line 6 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl2 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl3;
            
            #line 6 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl3 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl4;
            
            #line 6 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl4 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.PlaceHolder @__ctrl5;
            
            #line 6 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl5 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::Microsoft.AspNet.Web.Optimization.WebForms.BundleReference @__ctrl6;
            
            #line 6 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl6 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl7;
            
            #line 6 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl7 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl8;
            
            #line 6 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl8 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 6 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl9 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        146,
                        2203,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control13() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n<body>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2349,
                        14,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.ScriptReference @__BuildControl__control17() {
            global::System.Web.UI.ScriptReference @__ctrl;
            
            #line 65 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl = new global::System.Web.UI.ScriptReference();
            
            #line default
            #line hidden
            
            #line 65 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Name = "MsAjaxBundle";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.ScriptReference @__BuildControl__control18() {
            global::System.Web.UI.ScriptReference @__ctrl;
            
            #line 66 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl = new global::System.Web.UI.ScriptReference();
            
            #line default
            #line hidden
            
            #line 66 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Name = "jquery";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.ScriptReference @__BuildControl__control19() {
            global::System.Web.UI.ScriptReference @__ctrl;
            
            #line 67 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl = new global::System.Web.UI.ScriptReference();
            
            #line default
            #line hidden
            
            #line 67 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Name = "WebForms.js";
            
            #line default
            #line hidden
            
            #line 67 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Assembly = "System.Web";
            
            #line default
            #line hidden
            
            #line 67 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Path = "~/Scripts/WebForms/WebForms.js";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.ScriptReference @__BuildControl__control20() {
            global::System.Web.UI.ScriptReference @__ctrl;
            
            #line 68 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl = new global::System.Web.UI.ScriptReference();
            
            #line default
            #line hidden
            
            #line 68 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Name = "WebUIValidation.js";
            
            #line default
            #line hidden
            
            #line 68 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Assembly = "System.Web";
            
            #line default
            #line hidden
            
            #line 68 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Path = "~/Scripts/WebForms/WebUIValidation.js";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.ScriptReference @__BuildControl__control21() {
            global::System.Web.UI.ScriptReference @__ctrl;
            
            #line 69 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl = new global::System.Web.UI.ScriptReference();
            
            #line default
            #line hidden
            
            #line 69 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Name = "MenuStandards.js";
            
            #line default
            #line hidden
            
            #line 69 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Assembly = "System.Web";
            
            #line default
            #line hidden
            
            #line 69 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Path = "~/Scripts/WebForms/MenuStandards.js";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.ScriptReference @__BuildControl__control22() {
            global::System.Web.UI.ScriptReference @__ctrl;
            
            #line 70 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl = new global::System.Web.UI.ScriptReference();
            
            #line default
            #line hidden
            
            #line 70 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Name = "GridView.js";
            
            #line default
            #line hidden
            
            #line 70 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Assembly = "System.Web";
            
            #line default
            #line hidden
            
            #line 70 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Path = "~/Scripts/WebForms/GridView.js";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.ScriptReference @__BuildControl__control23() {
            global::System.Web.UI.ScriptReference @__ctrl;
            
            #line 71 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl = new global::System.Web.UI.ScriptReference();
            
            #line default
            #line hidden
            
            #line 71 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Name = "DetailsView.js";
            
            #line default
            #line hidden
            
            #line 71 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Assembly = "System.Web";
            
            #line default
            #line hidden
            
            #line 71 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Path = "~/Scripts/WebForms/DetailsView.js";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.ScriptReference @__BuildControl__control24() {
            global::System.Web.UI.ScriptReference @__ctrl;
            
            #line 72 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl = new global::System.Web.UI.ScriptReference();
            
            #line default
            #line hidden
            
            #line 72 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Name = "TreeView.js";
            
            #line default
            #line hidden
            
            #line 72 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Assembly = "System.Web";
            
            #line default
            #line hidden
            
            #line 72 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Path = "~/Scripts/WebForms/TreeView.js";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.ScriptReference @__BuildControl__control25() {
            global::System.Web.UI.ScriptReference @__ctrl;
            
            #line 73 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl = new global::System.Web.UI.ScriptReference();
            
            #line default
            #line hidden
            
            #line 73 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Name = "WebParts.js";
            
            #line default
            #line hidden
            
            #line 73 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Assembly = "System.Web";
            
            #line default
            #line hidden
            
            #line 73 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Path = "~/Scripts/WebForms/WebParts.js";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.ScriptReference @__BuildControl__control26() {
            global::System.Web.UI.ScriptReference @__ctrl;
            
            #line 74 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl = new global::System.Web.UI.ScriptReference();
            
            #line default
            #line hidden
            
            #line 74 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Name = "Focus.js";
            
            #line default
            #line hidden
            
            #line 74 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Assembly = "System.Web";
            
            #line default
            #line hidden
            
            #line 74 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Path = "~/Scripts/WebForms/Focus.js";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.ScriptReference @__BuildControl__control27() {
            global::System.Web.UI.ScriptReference @__ctrl;
            
            #line 75 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl = new global::System.Web.UI.ScriptReference();
            
            #line default
            #line hidden
            
            #line 75 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Path = "~/Scripts/jquery-ui-1.13.2.js";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.ScriptReference @__BuildControl__control28() {
            global::System.Web.UI.ScriptReference @__ctrl;
            
            #line 76 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl = new global::System.Web.UI.ScriptReference();
            
            #line default
            #line hidden
            
            #line 76 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Name = "WebFormsBundle";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control16(System.Web.UI.ScriptReferenceCollection @__ctrl) {
            global::System.Web.UI.ScriptReference @__ctrl1;
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl1 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.ScriptReference @__ctrl2;
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl2 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.ScriptReference @__ctrl3;
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl3 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.ScriptReference @__ctrl4;
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl4 = this.@__BuildControl__control20();
            
            #line default
            #line hidden
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.ScriptReference @__ctrl5;
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl5 = this.@__BuildControl__control21();
            
            #line default
            #line hidden
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Add(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.ScriptReference @__ctrl6;
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl6 = this.@__BuildControl__control22();
            
            #line default
            #line hidden
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Add(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.ScriptReference @__ctrl7;
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl7 = this.@__BuildControl__control23();
            
            #line default
            #line hidden
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Add(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.ScriptReference @__ctrl8;
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl8 = this.@__BuildControl__control24();
            
            #line default
            #line hidden
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Add(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.ScriptReference @__ctrl9;
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl9 = this.@__BuildControl__control25();
            
            #line default
            #line hidden
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Add(@__ctrl9);
            
            #line default
            #line hidden
            global::System.Web.UI.ScriptReference @__ctrl10;
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl10 = this.@__BuildControl__control26();
            
            #line default
            #line hidden
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Add(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.ScriptReference @__ctrl11;
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl11 = this.@__BuildControl__control27();
            
            #line default
            #line hidden
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Add(@__ctrl11);
            
            #line default
            #line hidden
            global::System.Web.UI.ScriptReference @__ctrl12;
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl12 = this.@__BuildControl__control28();
            
            #line default
            #line hidden
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.Add(@__ctrl12);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.ScriptManager @__BuildControl__control15() {
            global::System.Web.UI.ScriptManager @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.ScriptManager)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.ScriptManager))));
            }
            else {
                
                #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
                @__ctrl = new global::System.Web.UI.ScriptManager();
                
                #line default
                #line hidden
            }
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.EnableCdn = true;
            
            #line default
            #line hidden
            
            #line 61 "C:\Users\egrou\source\repos\food\food\Site.Master"
            this.@__BuildControl__control16(@__ctrl.Scripts);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2394,
                        1581,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control29() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("菜單系統");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4195,
                        4,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlAnchor @__BuildControlmenu_infor() {
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlAnchor)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlAnchor))));
            }
            else {
                
                #line 83 "C:\Users\egrou\source\repos\food\food\Site.Master"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlAnchor();
                
                #line default
                #line hidden
            }
            this.menu_infor = @__ctrl;
            
            #line 83 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.ID = "menu_infor";
            
            #line default
            #line hidden
            
            #line 83 "C:\Users\egrou\source\repos\food\food\Site.Master"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "navbar-brand");
            
            #line default
            #line hidden
            
            #line 83 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.HRef = "~/";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 83 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl1 = this.@__BuildControl__control29();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 83 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4130,
                        73,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control31() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("主頁面");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4788,
                        3,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlAnchor @__BuildControl__control30() {
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlAnchor)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlAnchor))));
            }
            else {
                
                #line 90 "C:\Users\egrou\source\repos\food\food\Site.Master"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlAnchor();
                
                #line default
                #line hidden
            }
            
            #line 90 "C:\Users\egrou\source\repos\food\food\Site.Master"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "nav-link");
            
            #line default
            #line hidden
            
            #line 90 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.HRef = "~/";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 90 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl1 = this.@__BuildControl__control31();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 90 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4743,
                        52,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control33() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("新增/編輯菜色");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4902,
                        7,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlAnchor @__BuildControl__control32() {
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlAnchor)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlAnchor))));
            }
            else {
                
                #line 91 "C:\Users\egrou\source\repos\food\food\Site.Master"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlAnchor();
                
                #line default
                #line hidden
            }
            
            #line 91 "C:\Users\egrou\source\repos\food\food\Site.Master"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "nav-link");
            
            #line default
            #line hidden
            
            #line 91 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.HRef = "~/New_dishes";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 91 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl1 = this.@__BuildControl__control33();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 91 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4847,
                        66,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control35() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("菜單管理");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5025,
                        4,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlAnchor @__BuildControl__control34() {
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlAnchor)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlAnchor))));
            }
            else {
                
                #line 92 "C:\Users\egrou\source\repos\food\food\Site.Master"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlAnchor();
                
                #line default
                #line hidden
            }
            
            #line 92 "C:\Users\egrou\source\repos\food\food\Site.Master"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "nav-link");
            
            #line default
            #line hidden
            
            #line 92 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.HRef = "~/Menu_management";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 92 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl1 = this.@__BuildControl__control35();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 92 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4965,
                        68,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control36() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("管理登入");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5152,
                        4,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlAnchor @__BuildControllogin_inout() {
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlAnchor)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlAnchor))));
            }
            else {
                
                #line 93 "C:\Users\egrou\source\repos\food\food\Site.Master"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlAnchor();
                
                #line default
                #line hidden
            }
            this.login_inout = @__ctrl;
            
            #line 93 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.ID = "login_inout";
            
            #line default
            #line hidden
            
            #line 93 "C:\Users\egrou\source\repos\food\food\Site.Master"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "nav-link");
            
            #line default
            #line hidden
            
            #line 93 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.HRef = "~/login";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 93 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl1 = this.@__BuildControl__control36();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 93 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5085,
                        75,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control37() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n            ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5368,
                        14,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ContentPlaceHolder @__BuildControlMainContent() {
            global::System.Web.UI.WebControls.ContentPlaceHolder @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.ContentPlaceHolder)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.ContentPlaceHolder))));
            }
            else {
                
                #line 99 "C:\Users\egrou\source\repos\food\food\Site.Master"
                @__ctrl = new global::System.Web.UI.WebControls.ContentPlaceHolder();
                
                #line default
                #line hidden
            }
            this.MainContent = @__ctrl;
            
            #line 99 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl.ID = "MainContent";
            
            #line default
            #line hidden
            if ((this.ContentTemplates != null)) {
                this.@__Template_MainContent = ((System.Web.UI.ITemplate)(this.ContentTemplates["MainContent"]));
            }
            if ((this.@__Template_MainContent != null)) {
                this.InstantiateInContentPlaceHolder(@__ctrl, this.@__Template_MainContent);
            }
            else {
                global::System.Web.UI.LiteralControl @__ctrl1;
                
                #line 99 "C:\Users\egrou\source\repos\food\food\Site.Master"
                @__ctrl1 = this.@__BuildControl__control37();
                
                #line default
                #line hidden
                System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
                
                #line 99 "C:\Users\egrou\source\repos\food\food\Site.Master"
                @__parser.AddParsedSubObject(@__ctrl1);
                
                #line default
                #line hidden
            }
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5312,
                        95,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControl__control14() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlForm)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlForm))));
            }
            else {
                
                #line 60 "C:\Users\egrou\source\repos\food\food\Site.Master"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
                
                #line default
                #line hidden
            }
            global::System.Web.UI.ScriptManager @__ctrl1;
            
            #line 60 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl1 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 60 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl2;
            
            #line 60 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl2 = this.@__BuildControlmenu_infor();
            
            #line default
            #line hidden
            
            #line 60 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl3;
            
            #line 60 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl3 = this.@__BuildControl__control30();
            
            #line default
            #line hidden
            
            #line 60 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl4;
            
            #line 60 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl4 = this.@__BuildControl__control32();
            
            #line default
            #line hidden
            
            #line 60 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl5;
            
            #line 60 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl5 = this.@__BuildControl__control34();
            
            #line default
            #line hidden
            
            #line 60 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl6;
            
            #line 60 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl6 = this.@__BuildControllogin_inout();
            
            #line default
            #line hidden
            
            #line 60 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ContentPlaceHolder @__ctrl7;
            
            #line 60 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl7 = this.@__BuildControlMainContent();
            
            #line default
            #line hidden
            
            #line 60 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control14));
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2363,
                        21,
                        false});
            return @__ctrl;
        }
        
        private void @__Render__control14(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Site.Master",
                        2384,
                        10,
                        true});
            @__w.Write("\r\n        ");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            parameterContainer.Controls[0].RenderControl(@__w);
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Site.Master",
                        3975,
                        155,
                        true});
            @__w.Write("\r\n\r\n        <nav class=\"navbar navbar-expand-sm navbar-toggleable-sm navbar-dark " +
                    "bg-dark fixed-top\">\r\n            <div class=\"container\">\r\n                ");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            parameterContainer.Controls[1].RenderControl(@__w);
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Site.Master",
                        4203,
                        540,
                        true});
            this.WriteUTF8ResourceString(@__w, 0, 548, false);
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            parameterContainer.Controls[2].RenderControl(@__w);
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Site.Master",
                        4795,
                        52,
                        true});
            @__w.Write("</li>\r\n                        <li class=\"nav-item\">");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            parameterContainer.Controls[3].RenderControl(@__w);
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Site.Master",
                        4913,
                        52,
                        true});
            @__w.Write("</li>\r\n                        <li class=\"nav-item\">");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            parameterContainer.Controls[4].RenderControl(@__w);
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Site.Master",
                        5033,
                        52,
                        true});
            @__w.Write("</li>\r\n                        <li class=\"nav-item\">");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            parameterContainer.Controls[5].RenderControl(@__w);
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Site.Master",
                        5160,
                        152,
                        true});
            @__w.Write("</li>\r\n                    </ul>\r\n                </div>\r\n            </div>\r\n   " +
                    "     </nav>\r\n        <div class=\"container body-content\">\r\n            ");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            parameterContainer.Controls[6].RenderControl(@__w);
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Site.Master",
                        5407,
                        70,
                        true});
            @__w.Write("\r\n            <hr />\r\n            <footer>\r\n                <p>&copy; ");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Site.Master",
                        5477,
                        24,
                        false});
            
            #line 103 "C:\Users\egrou\source\repos\food\food\Site.Master"
@__w.Write(System.Web.HttpUtility.HtmlEncode( DateTime.Now.Year ));

            
            #line default
            #line hidden
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Site.Master",
                        5501,
                        60,
                        true});
            @__w.Write(" - 服務體 菜單系統</p>\r\n            </footer>\r\n        </div>\r\n    ");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Site.Master",
                        5561,
                        7,
                        false});
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control38() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5568,
                        6,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.PlaceHolder @__BuildControl__control39() {
            global::System.Web.UI.WebControls.PlaceHolder @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.PlaceHolder)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.PlaceHolder))));
            }
            else {
                
                #line 107 "C:\Users\egrou\source\repos\food\food\Site.Master"
                @__ctrl = new global::System.Web.UI.WebControls.PlaceHolder();
                
                #line default
                #line hidden
            }
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control39));
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5574,
                        113,
                        false});
            return @__ctrl;
        }
        
        private void @__Render__control39(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Site.Master",
                        5616,
                        47,
                        false});
            
            #line 108 "C:\Users\egrou\source\repos\food\food\Site.Master"
@__w.Write(System.Web.HttpUtility.HtmlEncode( Scripts.Render("~/Scripts/bootstrap.js") ));

            
            #line default
            #line hidden
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control40() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n</body>\r\n</html>\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5687,
                        20,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(site_master @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 1 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl2;
            
            #line 1 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl2 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 1 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl3 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl4;
            
            #line 1 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl4 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 1 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl5 = this.@__BuildControl__control38();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.PlaceHolder @__ctrl6;
            
            #line 1 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl6 = this.@__BuildControl__control39();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 1 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__ctrl7 = this.@__BuildControl__control40();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\egrou\source\repos\food\food\Site.Master"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.site_master.@__stringResource, 0);
            this.@__BuildControlTree(this);
        }
    }
}
